#pragma config(Motor,  port6,           backleftwheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontleftwheel, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define DEADBAND 20

task main()
{



}
